all:
  vars:
    ansible_user: maks
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3

  children:
    domain_controllers:
      hosts:
        samba-dc:
          ansible_host: 192.168.122.10

    mail_servers:
      hosts:
        mail:
          ansible_host: 192.168.122.11

    proxies:
      hosts:
        nginx-proxy:
          ansible_host: 192.168.122.12

    monitoring:
      hosts:
        nginx-proxy:  # monitoring runs on proxy host via Docker

    all_vms:
      children:
        domain_controllers:
        mail_servers:
        proxies:
